Update to 1.0.0
appwrite/playground-for-node pull request #19
Opened 2022-09-15 04:34 UTC by abnegate

## What does this PR do?

Update to 1.0.0

## Test Plan

Manual test

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2022-09-16 00:03 UTC, stnguyen90 requested changes

2022-09-16 00:03 UTC, stnguyen90 commented on src/app.js
> +            Query.equal('release_year', 1920),
When I ran this, I got an error saying the index on `release_year` was not found:

```
AppwriteException [Error]: Index not found: release_year
    at Client.call (/workspace/playground-for-node/node_modules/node-appwrite/lib/client.js:171:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Databases.listDocuments (/workspace/playground-for-node/node_modules/node-appwrite/lib/services/databases.js:1004:16)
    at async listDocuments (/workspace/playground-for-node/src/app.js:128:22)
    at async runAllTasks (/workspace/playground-for-node/src/app.js:331:5) {
  code: 400,
  type: 'general_argument_invalid',
  response: {
    message: 'Index not found: release_year',
    code: 400,
    type: 'general_argument_invalid',
    version: '1.0.1'
  }
}
```

2022-09-16 00:08 UTC, stnguyen90 commented on src/app.js
> +    await new Promise((resolve) => setTimeout(resolve, 2000));
Add code to create index.

```suggestion
    await new Promise((resolve) => setTimeout(resolve, 2000));

    const yearIndexResponse = await databases.createIndex(
        databaseId,
        collectionId,
        'key_release_year_asc',
        'key',
        ['release_year'],
        ['ASC'],
    );
    console.log(yearIndexResponse);

    console.log("Waiting a little to ensure index is created ...");
    await new Promise((resolve) => setTimeout(resolve, 2000));
```

2022-09-16 00:09 UTC, stnguyen90 requested changes
Just missing index on release_year. Otherwise, LGTM!

2022-10-21 23:02 UTC, stnguyen90 commented on src/app.js
> +    await deleteCollection();
should we add `deleteDatabase()` too?

2022-10-24 22:38 UTC, abnegate commented on src/app.js
> +    await deleteCollection();
Added plus some more 👍

2022-10-25 22:40 UTC, stnguyen90 approved these changes

2022-11-04 08:43 UTC, merged